# Header
menu:
  Home: /
  About: about
  Join: join
  Calendar: calendar
  Tutoring: tutoring
  Innovation: innovation
  Hardware: hardware
  Sponsors: sponsors
  Contact Us: contact
  # Profiles: profiles
  # Blog: blog
# rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
# - archive
- recent_posts

# Miscellaneous
google_analytics: UA-54349005-1
favicon: css/images/favicon.png
twitter: gtieee
google_plus:
fb_admins:
fb_app_id:
